# Generated by Django 6.0 on 2026-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='arm',
        ),
        migrations.AddField(
            model_name='quiz',
            name='arms',
            field=models.ManyToManyField(blank=True, to='cbtapp.arm'),
        ),
    ]
