# Generated by Django 6.0 on 2026-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0002_arm_remove_quiz_arm_quiz_arms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arm',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='arms',
            field=models.ManyToManyField(blank=True, to='cbtapp.classarm'),
        ),
    ]
