# Generated by Django 6.0 on 2026-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0003_delete_arm_alter_quiz_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
