# Generated by Django 6.0 on 2026-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
