# Generated by Django 6.0 on 2026-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0005_question_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
