# Generated by Django 6.0 on 2026-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0006_remove_question_passage_quiz_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passage',
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
