# Generated by Django 6.0 on 2026-03-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0007_remove_quiz_passage_question_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='trial_duration_minutes',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trial_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('arms', models.ManyToManyField(blank=True, to='cbtapp.classarm')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtapp.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtapp.subject')),
            ],
        ),
    ]
