# Generated by Django 6.0 on 2026-03-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0008_studentprofile_trial_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_start_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_used',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
