# Generated by Django 6.0 on 2026-03-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0010_studentprofile_trial_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_used',
        ),
    ]
