# Generated by Django 6.0 on 2026-03-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0011_remove_studentprofile_trial_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='trial_start_time',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trial_questions_used',
            field=models.IntegerField(default=0),
        ),
    ]
