# Generated by Django 6.0 on 2026-04-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0013_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('title', 'subject', 'school_class'), name='unique_quiz_per_subject_class'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
