# Generated by Django 6.0 on 2026-05-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0015_examtype_remove_quiz_unique_quiz_per_subject_class_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_quiz_per_exam_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='exam_type',
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
    ]
