# Generated by Django 6.0 on 2026-05-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0016_remove_quiz_unique_quiz_per_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_quizzes', to='cbtapp.schoolclass'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_quizzes', to='cbtapp.schoolclass'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('title', 'subject', 'exam_type'), name='unique_quiz_per_exam_type'),
        ),
    ]
