# Generated by Django 6.0 on 2026-05-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0018_flashcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashCard',
        ),
    ]
