# Generated by Django 6.0 on 2026-05-06 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapp', '0019_delete_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('formula', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formula_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arms', models.ManyToManyField(blank=True, to='cbtapp.classarm')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtapp.schoolclass')),
            ],
        ),
    ]
